# Generated by Django 3.1.7 on 2021-03-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_order_order_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequenceO',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='name')),
                ('last', models.PositiveIntegerField(verbose_name='last value')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, default='s', max_length=7),
        ),
    ]
